name: AinurUHC
version: 1.0
author: Wolf_IV
main: com.Wolf_IV.AnuirUHC.MainA
commands: 
  startainuruhc:
    description: Starts Uhc
    permission: startuhc.use
  startainuruhcstop:
    description: Stop Uhc start
    permission: startuhcstop.use
  daypass:
    description: Pass the day
    permission: daypass.use
  arevive:
    description: Revive
    permission: arevive.use
  u:
    description: use power
  br:
    description: see balrog list
  don:
    description: donner silmarils
  claim:
    description: claim les silmarils